# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0484c07e6bfdea66165f29a9cce316817a69f53883d6db89ea5bf13cb56b7ab9f1d73501b7137f28207c2908aef48744e0b5a174045204cea0ded4f8e6d84be

test:
  secret_key_base: 943f8bc3c398e90571f8b94f620a16c2a0c4eec67ecd8698d8205cba39fb1e5fa6f281d1d5ab862e9444abe7b7608e66ccc35e2827016792aa2ae80247185bb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
